-A simple PHP Shopping Cart built with CakePHP PHP framework.
-
-- CakePHP 2.5 rapid development php framework
-- CakePHP DebugKit
-- Bootstrap 3 front-end framework with Mobile Friendly Responsive design
-- jQuery, jQuery UI JavaScript Library
-- Authorize.net Payment Gateway for Credit Card Payment
-- PayPal Express Checkout
-- AJAX functions for search autocomplete, shopping cart updates
-- Product Brands
-- Product Categories
-- Product Tags
-- Product Options
-
-INCOMPLETE !
-
-////////////////////////////////////////////////////////////////////
-
-CakePHP Shopping Cart Demo:
-
-http://www.shoppingcartcore.com
-
-//////////////////////////////////////////////////////////////////////////
-
-CakePHP Shopping Cart Installation:
-
-git clone https://github.com/andraskende/cakephp-shopping-cart.git cakephp-shopping-cart
-cd cakephp-shopping-cart
-chmod -R 777 app/tmp/
-mysql -u db_username -p db_password db_name < app/Config/Schema/shop.sql
-cp app/Config/settings-default.php app/Config/settings.php
-cp app/Config/database.php.default app/Config/database.php
-
-/admin
-username: admin
-password: admin
-
-Dont forget to change passwords, salt in core.php, etc...
-
-////////////////////////////////////////////////////////////////////
-
-http://andraskende.github.com/cakephp-shopping-cart
-
-http://www.shoppingcartcore.com
-
-Andras Kende http://www.kende.com